{
 "title": "Plex Service Management",
 "description": "Monitor Plex as a service including docker *arr collectors, disk arrays, and UPS - by u/SpinCharm",
 "tags": [
  "Varken",
  "Plex",
  "Tautulli",
  "Sonarr",
  "Radarr"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "movieslibrary", "label": "Movies Library Name", "query": "${VAR_MOVIESLIBRARY}" },
   { "name": "movies4klibrary", "label": "4K Movies Library Name", "query": "${VAR_MOVIES4KLIBRARY}" },
   { "name": "tvlibrary", "label": "TV Library Name", "query": "${VAR_TVLIBRARY}" },
   { "name": "tv4klibrary", "label": "TV 4K Library Name", "query": "${VAR_TV4KLIBRARY}" },
   { "name": "ombiurl", "label": "Ombi URL", "query": "${VAR_OMBIURL}" },
   { "name": "tautulliurl", "label": "Tautulli URL", "query": "${VAR_TAUTULLIURL}" },
   { "name": "sonarrurl", "label": "Sonarr URL", "query": "${VAR_SONARRURL}" },
   { "name": "radarrurl", "label": "Radarr URL", "query": "${VAR_RADARRURL}" },
   { "name": "sickchillurl", "label": "Sickchill URL", "query": "${VAR_SICKCHILLURL}" },
   { "name": "movies3dlibrary", "label": "3D Movies Library Name", "query": "${VAR_MOVIES3DLIBRARY}" },
   { "name": "moviesxmaslibrary", "label": "Christmas Movies Library Name", "query": "${VAR_MOVIESXMASLIBRARY}" },
   { "name": "showsxmaslibrary", "label": "Xmas Shows Library Name", "query": "${VAR_SHOWSXMASLIBRARY}" },
   { "name": "musicxmaslibrary", "label": "Xmas Music", "query": "${VAR_MUSICXMASLIBRARY}" },
   { "name": "Datasource_Telegraf", "label": "Telegraf Datasource", "query": "${VAR_DATASOURCE_TELEGRAF}" },
   { "name": "Host", "label": "Host", "query": "${VAR_HOST}" },
   { "name": "CPU_Threads", "label": "CPU Threads", "query": "${VAR_CPU_THREADS}" },
   { "name": "UPS_Max_Watts", "label": "UPS Max Output (Watts)", "query": "${VAR_UPS_MAX_WATTS}" },
   { "name": "UPS_kWh_Price", "label": "kWh Price", "query": "${VAR_UPS_KWH_PRICE}" },
   { "name": "Currency", "label": "Currency", "query": "${VAR_CURRENCY}" },
   {
    "name": "Docker_Stack",
    "label": "Docker_Stack",
    "query": "SHOW TAG VALUES WITH KEY = \"docker.group\"  "
   },
   {
    "name": "url_name",
    "label": "URL",
    "query": "SHOW TAG VALUES FROM http_response WITH KEY=server"
   }
  ]
 },
 "panels": [
  { "title": "Plex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Streams",
   "type": "table",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "audio_codec" ], "type": "tag" },
      { "params": [ "device_type" ], "type": "tag" },
      { "params": [ "full_location" ], "type": "tag" },
      { "params": [ "media_type" ], "type": "tag" },
      { "params": [ "product" ], "type": "tag" },
      { "params": [ "product_version" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" },
      { "params": [ "quality_profile" ], "type": "tag" },
      { "params": [ "relayed" ], "type": "tag" },
      { "params": [ "secure" ], "type": "tag" },
      { "params": [ "stream_audio_codec" ], "type": "tag" },
      { "params": [ "title" ], "type": "tag" },
      { "params": [ "transcode_decision" ], "type": "tag" },
      { "params": [ "username" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" },
      { "params": [ "quality_profile" ], "type": "tag" },
      { "params": [ "player_state" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "region_code" ], "type": "tag" },
      { "params": [ "progress_percent" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "query": "SELECT distinct(\"hash\") FROM \"Tautulli\" WHERE (\"type\" = 'Session') AND $timeFilter GROUP BY time($__interval), \"audio_codec\", \"device_type\", \"full_location\", \"media_type\", \"product\", \"product_version\", \"quality\", \"quality_profile\", \"relayed\", \"secure\", \"stream_audio_codec\", \"title\", \"transcode_decision\", \"username\", \"quality\", \"quality_profile\", \"player_state\", \"location\", \"region_code\", \"progress_percent\" ORDER BY time DESC",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Stream Log",
   "type": "table",
   "description": "Limited to Last 1,000 Entries",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "audio_codec" ], "type": "tag" },
      { "params": [ "device_type" ], "type": "tag" },
      { "params": [ "full_location" ], "type": "tag" },
      { "params": [ "media_type" ], "type": "tag" },
      { "params": [ "product" ], "type": "tag" },
      { "params": [ "product_version" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" },
      { "params": [ "quality_profile" ], "type": "tag" },
      { "params": [ "relayed" ], "type": "tag" },
      { "params": [ "secure" ], "type": "tag" },
      { "params": [ "stream_audio_codec" ], "type": "tag" },
      { "params": [ "title" ], "type": "tag" },
      { "params": [ "transcode_decision" ], "type": "tag" },
      { "params": [ "username" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" },
      { "params": [ "quality_profile" ], "type": "tag" },
      { "params": [ "player_state" ], "type": "tag" },
      { "params": [ "region_code" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "query": "SELECT distinct(\"hash\") FROM \"Tautulli\" WHERE (\"type\" = 'Session') AND $timeFilter GROUP BY time($interval), \"audio_codec\", \"device_type\", \"full_location\", \"media_type\", \"product\", \"product_version\", \"quality\", \"quality_profile\", \"relayed\", \"secure\", \"stream_audio_codec\", \"title\", \"transcode_decision\", \"username\", \"quality\", \"quality_profile\", \"player_state\", \"region_code\" ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Services Status",
   "type": "table",
   "description": "\n",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server_friendly" ], "type": "tag" }
     ],
     "measurement": "http_response",
     "query": "SELECT last(\"http_response_code\") FROM \"http_response\" WHERE (\"server\" =~ /^$url_name$/) AND $timeFilter GROUP BY server",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 5, "x": 4, "y": 12 },
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_region_code",
     "groupBy": [
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "full_location" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Stream Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "wan_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "WAN" ], "type": "alias" }
      ],
      [
       { "params": [ "lan_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "LAN" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "stream_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Direct Stream",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "direct_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Transocde Streams",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "transcode_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Server Popularity",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 10, "x": 9, "y": 18 },
   "targets": [
    {
     "alias": ".",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Direct Play Streams",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "direct_play_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "WAN BW",
   "type": "stat",
   "description": "Streaming Brain Estimate",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "wan_bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  { "title": "Plex Library", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Recent TV",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "TV Seasons",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "seasons" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "TV Episodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Media Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 25 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_media_type",
     "groupBy": [
      { "params": [ "media_type" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Media Qualities",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 25 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_quality",
     "groupBy": [
      { "params": [ "quality" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "TV Ep. (Day)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "TV Show Episodes (Day)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "section_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  {
   "title": "TV Episodes (Week)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "TV Show Episodes (Day)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "section_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  {
   "title": "TV Episodes (Month)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "TV Show Episodes (Week)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "section_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  {
   "title": "Recent Movies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$movieslibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$movieslibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "4K Movies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$movies4klibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "3D Movies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$movies3dlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Movies (Day)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Movies (Day)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "section_name", "operator": "=", "value": "Movies" }
     ]
    }
   ]
  },
  {
   "title": "Movies (Week)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Movies (Day)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "section_name", "operator": "=", "value": "Movies" }
     ]
    }
   ]
  },
  {
   "title": "Movies (Month)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Movies (Month)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "section_name", "operator": "=", "value": "Movies" }
     ]
    }
   ]
  },
  {
   "title": "Device Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 32 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_device_type",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "device_type" ], "type": "tag" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Stream Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 32 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_video_decision",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "video_decision" ], "type": "tag" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Xmas Movies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$moviesxmaslibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Xmas Shows",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$showsxmaslibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Xmas Albums",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$musicxmaslibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Xmas Tracks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Xmas Tracks",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "tracks" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$musicxmaslibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Music (Week)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Music Tracks (Week)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "tracks" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "section_name", "operator": "=", "value": "Music" }
     ]
    }
   ]
  },
  {
   "title": "Music Tracks (Month)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Music Tracks (Day)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "tracks" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "section_name", "operator": "=", "value": "Music" }
     ]
    }
   ]
  },
  {
   "title": "Tracks (Year)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Music Tracks (Day)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "tracks" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "section_name", "operator": "=", "value": "Music" }
     ]
    }
   ]
  },
  { "title": "Downloaders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "TV Shows on Today (Sonarr)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 41 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "downloaded" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "query": "SELECT distinct(\"hash\") FROM \"Sonarr\" WHERE (\"type\" = 'Future') AND $timeFilter GROUP BY \"downloaded\", \"name\", \"sxe\"",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Future" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows in Queue",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 41 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "protocol_id" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Queue" }
     ]
    }
   ]
  },
  {
   "title": "Missing TV Shows (Last 7 Days)",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 41 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Missing" }
     ]
    }
   ]
  },
  {
   "title": "Movies in Queue",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 41 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "protocol_id" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" }
     ],
     "measurement": "Radarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Queue" }
     ]
    }
   ]
  },
  {
   "title": "Missing Available Movies",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 41 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "titleSlug" ], "type": "tag" }
     ],
     "measurement": "Radarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Missing_Available", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Ombi Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "title" ], "type": "tag" },
      { "params": [ "requested_date" ], "type": "tag" },
      { "params": [ "requested_user" ], "type": "tag" },
      { "params": [ "request_type" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Requests" },
      { "condition": "AND", "key": "status", "operator": "!=", "value": "0" },
      { "condition": "AND", "key": "status", "operator": "!=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Req. Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "pending" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Requests Approved",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "approved" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Requests Done",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "available" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Issues In Progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "in_progress" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Issues_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Issues Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "pending" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Issues_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Issues Resolved",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "resolved" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Issues_Counts" }
     ]
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Stopped Docker",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 2, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name IO_write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_write"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_container_name IO_read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_read"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Running Docker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "Systems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1+100" ], "type": "math" },
       { "params": [ "Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Iowait" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Nice" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "User" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Softirq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "System" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "feature" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "chip", "operator": "=", "value": "nouveau-pci-a100" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sophie" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "temp1" }
     ]
    },
    {
     "alias": "NIC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "feature" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "chip", "operator": "=", "value": "enp2s0-pci-0200" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sophie" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "phy_temperature" }
     ]
    },
    {
     "alias": "$tag_feature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "feature" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "temp_input", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sophie" },
      { "condition": "AND", "key": "feature", "operator": "!~", "value": "/core*/" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "nct6796-isa-0290" }
     ]
    }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "graph",
   "description": "Note: Uses REGEX to Parse Fan Names From IPMI Sensor List!",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    {
     "alias": "case left",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "fan_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "fan3" }
     ]
    },
    {
     "alias": "case right",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "sensors",
     "query": "SELECT non_negative_derivative(mean(fan_input),1s) FROM \"sensors\" WHERE (\"feature\" = 'fan1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "fan_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "fan1" }
     ]
    },
    {
     "alias": "disk left",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "fan_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "fan2" }
     ]
    },
    {
     "alias": "disk centre",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "fan_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "fan7" }
     ]
    },
    {
     "alias": "disk right",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "fan_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "fan4" }
     ]
    },
    {
     "alias": "water pump",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "fan_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "fan6" }
     ]
    },
    {
     "alias": "GPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "fan_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "fan1" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "nouveau-pci-a100" }
     ]
    }
   ]
  },
  {
   "title": "1GBe Network (br0)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(last(\"bytes_sent\"), 1s) FROM \"net\" WHERE (\"interface\" = 'br0' AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "br0" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(last(\"bytes_recv\"), 1s) FROM \"net\" WHERE (\"host\" =~ /^$host$/ AND \"interface\" = 'eth0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "br0" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM DIMM Temps ",
   "type": "graph",
   "description": "Note: Uses IPMI & REGEX",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "SELECT last(\"value\") FROM \"sensors\" WHERE (\"feature\" = 'auxtin0' AND \"host\" ='sophie') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "auxtin0" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sophie" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "nct6796-isa-0290" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "SELECT last(\"value\") FROM \"sensors\" WHERE (\"feature\" = 'auxtin0' AND \"host\" ='sophie') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "auxtin1" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sophie" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "nct6796-isa-0290" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "SELECT last(\"value\") FROM \"sensors\" WHERE (\"feature\" = 'auxtin0' AND \"host\" ='sophie') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "auxtin2" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sophie" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "nct6796-isa-0290" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "SELECT last(\"value\") FROM \"sensors\" WHERE (\"feature\" = 'auxtin0' AND \"host\" ='sophie') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "auxtin3" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sophie" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "nct6796-isa-0290" }
     ]
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Disk Storage",
   "type": "table",
   "description": "Note: Uses Variable",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 77 },
   "targets": [
    {
     "alias": "Disk 1",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used\")  / 1000000000000 AS \"Used\", last(\"free\")  / 1000000000000 AS \"Free\", last(\"total\")  / 1000000000000 AS \"Total\", last(\"used_percent\") AS \"Used %\" FROM \"disk\" WHERE (\"host\" = 'sophie' OR \"path\" = '/media/management' OR \"path\" = '/media/systems' OR \"path\" = '/' AND \"path\" <> '/var/lib/docker' AND \"fstype\" <> 'rootfs' AND \"path\" <> '/mnt/user' AND \"path\" <> '/mnt/user0' AND \"path\" <> '/mnt/cache' AND \"path\" !~ /^$Path_Unassigned$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY \"path\", \"device\", \"fstype\"",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Used %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sophie" }
     ]
    }
   ]
  },
  {
   "title": "Array Drive Temps",
   "type": "graph",
   "description": "User Overrides > Display Name to Dynamically Name Serial Number (Field Name) to Drive Number",
   "gridPos": { "h": 10, "w": 6, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "serial_no" ], "type": "tag" }
     ],
     "measurement": "smart_device",
     "query": "SELECT last(\"temp_c\") FROM \"smart_device\" WHERE (\"device\" = 'sg3' OR \"device\" = 'sg4' OR \"device\" = 'sg5' OR \"device\" = 'sg1' ) AND \"host\" =~ /^$Host$/ AND $timeFilter GROUP BY time($__interval), \"serial_no\"",
     "select": [
      [
       { "params": [ "temp_c" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$areca_dev$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Non-Array Drive Temps",
   "type": "graph",
   "description": "User Overrides > Display Name to Dynamically Name Serial Number (Field Name) to Drive Number",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 77 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_serial_no",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "serial_no" ], "type": "tag" }
     ],
     "measurement": "smart_device",
     "query": "SELECT last(\"temp_c\") FROM \"smart_device\" WHERE (\"device\" != 'sg3' AND \"device\" != 'sg4' AND \"device\" != 'sg5'  AND \"device\" != 'sg1' ) AND \"host\" =~ /^$Host$/ AND $timeFilter GROUP BY time($__interval), \"serial_no\"",
     "select": [
      [
       { "params": [ "temp_c" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "!~", "value": "/^$areca_dev$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Drive S.M.A.R.T. Health Overview",
   "type": "table",
   "description": "Note: Uses REGEX",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 87 },
   "targets": [
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "model" ], "type": "tag" },
      { "params": [ "serial_no" ], "type": "tag" },
      { "params": [ "fail" ], "type": "tag" },
      { "params": [ "flags" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Temp (C)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Temperature_Celsius" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_device",
     "query": "SELECT last(\"health_ok\") AS \"Health OK?\" FROM \"smart_device\" WHERE (\"device\" =~ /.*/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY \"device\"",
     "select": [
      [
       { "params": [ "health_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Health OK?" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      {
       "condition": "AND",
       "key": " ",
       "operator": ">",
       "value": "\"\""
      }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Current Pending Sectors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Current_Pending_Sector" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Reallocated Sectors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Reallocated_Sector_Ct" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Reallocated Events" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Reallocated_Event_Count" },
      {
       "condition": "AND",
       "key": "device",
       "operator": "<>",
       "value": "\"\""
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Offline/Uncorrectable" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Offline_Uncorrectable" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Power On Hours" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Power_On_Hours" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Power Cycles" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Power_Cycle_Count" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "model" ], "type": "tag" },
      { "params": [ "serial_no" ], "type": "tag" },
      { "params": [ "fail" ], "type": "tag" },
      { "params": [ "flags" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Temp (C)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Airflow_Temperature_Cel" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "sde" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "UPS Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "UPS Load %",
   "type": "graph",
   "description": "Note: Uses Variables",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT last(\"load_percent\") FROM \"apcupsd\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "UPS Load" ], "type": "alias" }
      ],
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* .01 * $UPS_Max_Watts" ], "type": "math" },
       { "params": [ "Watts" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "ups_name", "operator": "=", "value": "SophieUPS" }
     ]
    }
   ]
  },
  {
   "title": "UPS Load Vs. Time Left",
   "type": "graph",
   "description": "Note: Uses Variables",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 94 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* .01 * $UPS_Max_Watts" ], "type": "math" },
       { "params": [ "Watts" ], "type": "alias" }
      ],
      [
       { "params": [ "time_left_ns" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Time Left" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "ups_name", "operator": "=", "value": "SophieUPS" }
     ]
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current Input V",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "input_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "ups_name", "operator": "=", "value": "SophieUPS" }
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UPS Battery %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "battery_charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sophie" },
      { "condition": "AND", "key": "ups_name", "operator": "=", "value": "SophieUPS" }
     ]
    }
   ]
  },
  {
   "title": "Current Load",
   "type": "stat",
   "description": "Note: Uses Variables",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current Load W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* .01 * $UPS_Max_Watts" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "ups_name", "operator": "=", "value": "SophieUPS" }
     ]
    }
   ]
  },
  {
   "title": "Current Load kWh",
   "type": "stat",
   "description": "Note: Uses Variables",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* .01 * $UPS_Max_Watts/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "ups_name", "operator": "=", "value": "SophieUPS" }
     ]
    }
   ]
  },
  {
   "title": "Est. Monthly ",
   "type": "stat",
   "description": "Note:  Uses Variables | Adjust Field  Unit For Your Set UPS Currency Variable As Required!",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Estimated Monthly Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "* .01 * $UPS_Max_Watts/1000*24*$UPS_kWh_Price*365/12"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "ups_name", "operator": "=", "value": "SophieUPS" }
     ]
    }
   ]
  },
  {
   "title": "Average UPS Load",
   "type": "stat",
   "description": "Note: Uses Variables",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Average W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* .01 *  $UPS_Max_Watts" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "ups_name", "operator": "=", "value": "SophieUPS" }
     ]
    }
   ]
  }
 ]
}